
INSERT INTO marca_bus (nombre) VALUES
                                   ('Volvo'),
                                   ('Scania'),
                                   ('Fiat'),
                                   ('Mercedes Benz'),
                                   ('MAN'),
                                   ('Iveco'),
                                   ('Renault'),
                                   ('Volkswagen'),
                                   ('Hyundai'),
                                   ('BYD'),
                                   ('Yutong'),
                                   ('King Long'),
                                   ('Solaris'),
                                   ('Marcopolo'),
                                   ('Neoplan'),
                                   ('Setra'),
                                   ('Van Hool'),
                                   ('Prevost')
    ON DUPLICATE KEY UPDATE nombre = VALUES(nombre);


INSERT INTO bus (numero_bus, placa, fecha_creacion, caracteristicas, marca_id, activo) VALUES
                                                                                           ('BUS-0001', 'A-001-BC', NOW(), '40 asientos, Aire acondicionado, WiFi, USB, TV', 1, true),
                                                                                           ('BUS-0002', 'B-002-CD', NOW(), '50 asientos, Baño químico, TV, WiFi, Café, USB', 2, true),
                                                                                           ('BUS-0003', 'C-003-DE', NOW(), '30 asientos ejecutivos, Asientos reclinables, Entretenimiento, Bar', 3, false),
                                                                                           ('BUS-0004', 'D-004-EF', NOW(), '45 asientos, Aire acondicionado, Baño, TV, WiFi', 4, true),
                                                                                           ('BUS-0005', 'E-005-FG', NOW(), '35 asientos, Panorámico, WiFi, USB, Entretenimiento, Luces LED', 5, true),
                                                                                           ('BUS-0006', 'F-006-GH', NOW(), '55 asientos, Doble piso, Baño, Cafetería, TV, WiFi', 6, false),
                                                                                           ('BUS-0007', 'G-007-HI', NOW(), '25 asientos, VIP, Asientos cama, WiFi premium, Entretenimiento', 7, true),
                                                                                           ('BUS-0008', 'H-008-IJ', NOW(), '48 asientos, Económico, Aire acondicionado, USB', 8, true),
                                                                                           ('BUS-0009', 'I-009-JK', NOW(), '52 asientos, Estándar, Baño, TV, Aire acondicionado', 9, false),
                                                                                           ('BUS-0010', 'J-010-KL', NOW(), '38 asientos, Ejecutivo, Asientos amplios, WiFi, USB, TV', 10, true),
                                                                                           ('BUS-0011', 'K-011-LM', NOW(), '42 asientos, Premium, Asientos semi-cama, WiFi, Entretenimiento', 11, true),
                                                                                           ('BUS-0012', 'L-012-MN', NOW(), '60 asientos, Turístico, Baño, TV, WiFi, USB, Cafetería', 12, false),
                                                                                           ('BUS-0013', 'M-013-NO', NOW(), '40 asientos, Aire acondicionado, WiFi, USB, Ruta Costa', 13, true),
                                                                                           ('BUS-0014', 'N-014-OP', NOW(), '50 asientos, Baño, TV, WiFi, Ruta Sierra', 14, true),
                                                                                           ('BUS-0015', 'O-015-PQ', NOW(), '30 asientos ejecutivos, Asientos reclinables, Ruta Selva', 15, false),
                                                                                           ('BUS-0016', 'P-016-QR', NOW(), '45 asientos, Aire acondicionado, Baño, Ruta Norte', 16, true),
                                                                                           ('BUS-0017', 'Q-017-RS', NOW(), '35 asientos, Panorámico, WiFi, Ruta Sur', 17, true),
                                                                                           ('BUS-0018', 'R-018-ST', NOW(), '55 asientos, Doble piso, Baño, Ruta Centro', 18, false),
                                                                                           ('BUS-0019', 'S-019-TU', NOW(), '25 asientos, VIP, Asientos cama, Ruta Internacional', 1, true),
                                                                                           ('BUS-0020', 'T-020-UV', NOW(), '48 asientos, Económico, Aire acondicionado, Ruta Local', 2, true),
                                                                                           ('BUS-0021', 'U-021-VW', NOW(), '52 asientos, Estándar, Baño, Ruta Expresa', 3, false),
                                                                                           ('BUS-0022', 'V-022-WX', NOW(), '38 asientos, Ejecutivo, Asientos amplios, Ruta Nocturna', 4, true),
                                                                                           ('BUS-0023', 'W-023-XY', NOW(), '42 asientos, Premium, Asientos semi-cama, Ruta Diurna', 5, true),
                                                                                           ('BUS-0024', 'X-024-YZ', NOW(), '60 asientos, Turístico, Baño, Ruta Panorámica', 6, false),
                                                                                           ('BUS-0025', 'Y-025-ZA', NOW(), '40 asientos, Aire acondicionado, WiFi, Ruta Valles', 7, true),
                                                                                           ('BUS-0026', 'Z-026-AB', NOW(), '50 asientos, Baño, TV, Ruta Montaña', 8, true),
                                                                                           ('BUS-0027', 'AA-027-BC', NOW(), '30 asientos ejecutivos, Asientos reclinables, Ruta Desierto', 9, false),
                                                                                           ('BUS-0028', 'AB-028-CD', NOW(), '45 asientos, Aire acondicionado, Baño, Ruta Jungle', 10, true),
                                                                                           ('BUS-0029', 'AC-029-DE', NOW(), '35 asientos, Panorámico, WiFi, Ruta Andina', 11, true),
                                                                                           ('BUS-0030', 'AD-030-EF', NOW(), '55 asientos, Doble piso, Baño, Ruta Imperial', 12, false),
                                                                                           ('BUS-0031', 'AE-031-FG', NOW(), '25 asientos, VIP, Asientos cama, Ruta Colonial', 13, true),
                                                                                           ('BUS-0032', 'AF-032-GH', NOW(), '48 asientos, Económico, Aire acondicionado, Ruta Moderna', 14, true),
                                                                                           ('BUS-0033', 'AG-033-HI', NOW(), '52 asientos, Estándar, Baño, Ruta Antigua', 15, false),
                                                                                           ('BUS-0034', 'AH-034-IJ', NOW(), '38 asientos, Ejecutivo, Asientos amplios, Ruta Nueva', 16, true),
                                                                                           ('BUS-0035', 'AI-035-JK', NOW(), '42 asientos, Premium, Asientos semi-cama, Ruta Especial', 17, true),
                                                                                           ('BUS-0036', 'AJ-036-KL', NOW(), '60 asientos, Turístico, Baño, Ruta Turística', 18, false),
                                                                                           ('BUS-0037', 'AK-037-LM', NOW(), '40 asientos, Aire acondicionado, WiFi, Ruta Ejecutiva', 1, true),
                                                                                           ('BUS-0038', 'AL-038-MN', NOW(), '50 asientos, Baño, TV, Ruta Empresarial', 2, true),
                                                                                           ('BUS-0039', 'AM-039-NO', NOW(), '30 asientos ejecutivos, Asientos reclinables, Ruta Corporativa', 3, false),
                                                                                           ('BUS-0040', 'AN-040-OP', NOW(), '45 asientos, Aire acondicionado, Baño, Ruta Premium', 4, true),
                                                                                           ('BUS-0041', 'AO-041-PQ', NOW(), '35 asientos, Panorámico, WiFi, Ruta Gold', 5, true),
                                                                                           ('BUS-0042', 'AP-042-QR', NOW(), '55 asientos, Doble piso, Baño, Ruta Platinum', 6, false),
                                                                                           ('BUS-0043', 'AQ-043-RS', NOW(), '25 asientos, VIP, Asientos cama, Ruta Diamond', 7, true),
                                                                                           ('BUS-0044', 'AR-044-ST', NOW(), '48 asientos, Económico, Aire acondicionado, Ruta Standard', 8, true),
                                                                                           ('BUS-0045', 'AS-045-TU', NOW(), '52 asientos, Estándar, Baño, Ruta Básica', 9, false),
                                                                                           ('BUS-0046', 'AT-046-UV', NOW(), '38 asientos, Ejecutivo, Asientos amplios, Ruta Avanzada', 10, true),
                                                                                           ('BUS-0047', 'AU-047-VW', NOW(), '42 asientos, Premium, Asientos semi-cama, Ruta Superior', 11, true),
                                                                                           ('BUS-0048', 'AV-048-WX', NOW(), '60 asientos, Turístico, Baño, Ruta Deluxe', 12, false),
                                                                                           ('BUS-0049', 'AW-049-XY', NOW(), '40 asientos, Aire acondicionado, WiFi, Ruta Express', 13, true),
                                                                                           ('BUS-0050', 'AX-050-YZ', NOW(), '50 asientos, Baño, TV, Ruta Rapid', 14, true),
                                                                                           ('BUS-0051', 'AY-051-ZA', NOW(), '30 asientos ejecutivos, Asientos reclinables, Ruta Flash', 15, false),
                                                                                           ('BUS-0052', 'AZ-052-AB', NOW(), '45 asientos, Aire acondicionado, Baño, Ruta Speed', 16, true),
                                                                                           ('BUS-0053', 'BA-053-BC', NOW(), '35 asientos, Panorámico, WiFi, Ruta Directa', 17, true),
                                                                                           ('BUS-0054', 'BB-054-CD', NOW(), '55 asientos, Doble piso, Baño, Ruta Única', 18, false),
                                                                                           ('BUS-0055', 'BC-055-DE', NOW(), '25 asientos, VIP, Asientos cama, Ruta Especial', 1, true),
                                                                                           ('BUS-0056', 'BD-056-EF', NOW(), '48 asientos, Económico, Aire acondicionado, Ruta Regular', 2, true),
                                                                                           ('BUS-0057', 'BE-057-FG', NOW(), '52 asientos, Estándar, Baño, Ruta Frecuente', 3, false),
                                                                                           ('BUS-0058', 'BF-058-GH', NOW(), '38 asientos, Ejecutivo, Asientos amplios, Ruta Ocasional', 4, true),
                                                                                           ('BUS-0059', 'BG-059-HI', NOW(), '42 asientos, Premium, Asientos semi-cama, Ruta Programada', 5, true),
                                                                                           ('BUS-0060', 'BH-060-IJ', NOW(), '60 asientos, Turístico, Baño, Ruta Demanda', 6, false),
                                                                                           ('BUS-0061', 'BI-061-JK', NOW(), '40 asientos, Aire acondicionado, WiFi, Ruta Flexible', 7, true),
                                                                                           ('BUS-0062', 'BJ-062-KL', NOW(), '50 asientos, Baño, TV, Ruta Variable', 8, true),
                                                                                           ('BUS-0063', 'BK-063-LM', NOW(), '30 asientos ejecutivos, Asientos reclinables, Ruta Alterna', 9, false),
                                                                                           ('BUS-0064', 'BL-064-MN', NOW(), '45 asientos, Aire acondicionado, Baño, Ruta Principal', 10, true),
                                                                                           ('BUS-0065', 'BM-065-NO', NOW(), '35 asientos, Panorámico, WiFi, Ruta Secundaria', 11, true),
                                                                                           ('BUS-0066', 'BN-066-OP', NOW(), '55 asientos, Doble piso, Baño, Ruta Terciaria', 12, false),
                                                                                           ('BUS-0067', 'BO-067-PQ', NOW(), '25 asientos, VIP, Asientos cama, Ruta Urbana', 13, true),
                                                                                           ('BUS-0068', 'BP-068-QR', NOW(), '48 asientos, Económico, Aire acondicionado, Ruta Rural', 14, true),
                                                                                           ('BUS-0069', 'BQ-069-RS', NOW(), '52 asientos, Estándar, Baño, Ruta Interurbana', 15, false),
                                                                                           ('BUS-0070', 'BR-070-ST', NOW(), '38 asientos, Ejecutivo, Asientos amplios, Ruta Provincial', 16, true),
                                                                                           ('BUS-0071', 'BS-071-TU', NOW(), '42 asientos, Premium, Asientos semi-cama, Ruta Regional', 17, true),
                                                                                           ('BUS-0072', 'BT-072-UV', NOW(), '60 asientos, Turístico, Baño, Ruta Nacional', 18, false),
                                                                                           ('BUS-0073', 'BU-073-VW', NOW(), '40 asientos, Aire acondicionado, WiFi, Ruta Internacional', 1, true),
                                                                                           ('BUS-0074', 'BV-074-WX', NOW(), '50 asientos, Baño, TV, Ruta Fronteriza', 2, true),
                                                                                           ('BUS-0075', 'BW-075-XY', NOW(), '30 asientos ejecutivos, Asientos reclinables, Ruta Costera', 3, false),
                                                                                           ('BUS-0076', 'BX-076-YZ', NOW(), '45 asientos, Aire acondicionado, Baño, Ruta Andina', 4, true),
                                                                                           ('BUS-0077', 'BY-077-ZA', NOW(), '35 asientos, Panorámico, WiFi, Ruta Amazónica', 5, true),
                                                                                           ('BUS-0078', 'BZ-078-AB', NOW(), '55 asientos, Doble piso, Baño, Ruta Selvática', 6, false),
                                                                                           ('BUS-0079', 'CA-079-BC', NOW(), '25 asientos, VIP, Asientos cama, Ruta Lacustre', 7, true),
                                                                                           ('BUS-0080', 'CB-080-CD', NOW(), '48 asientos, Económico, Aire acondicionado, Ruta Fluvial', 8, true),
                                                                                           ('BUS-0081', 'CC-081-DE', NOW(), '52 asientos, Estándar, Baño, Ruta Marítima', 9, false),
                                                                                           ('BUS-0082', 'CD-082-EF', NOW(), '38 asientos, Ejecutivo, Asientos amplios, Ruta Aérea', 10, true),
                                                                                           ('BUS-0083', 'CE-083-FG', NOW(), '42 asientos, Premium, Asientos semi-cama, Ruta Terrestre', 11, true),
                                                                                           ('BUS-0084', 'CF-084-GH', NOW(), '60 asientos, Turístico, Baño, Ruta Ferroviaria', 12, false),
                                                                                           ('BUS-0085', 'CG-085-HI', NOW(), '40 asientos, Aire acondicionado, WiFi, Ruta Metropolitana', 13, true),
                                                                                           ('BUS-0086', 'CH-086-IJ', NOW(), '50 asientos, Baño, TV, Ruta Suburbana', 14, true),
                                                                                           ('BUS-0087', 'CI-087-JK', NOW(), '30 asientos ejecutivos, Asientos reclinables, Ruta Periurbana', 15, false),
                                                                                           ('BUS-0088', 'CJ-088-KL', NOW(), '45 asientos, Aire acondicionado, Baño, Ruta Comercial', 16, true),
                                                                                           ('BUS-0089', 'CK-089-LM', NOW(), '35 asientos, Panorámico, WiFi, Ruta Industrial', 17, true),
                                                                                           ('BUS-0090', 'CL-090-MN', NOW(), '55 asientos, Doble piso, Baño, Ruta Turística', 18, false),
                                                                                           ('BUS-0091', 'CM-091-NO', NOW(), '25 asientos, VIP, Asientos cama, Ruta Cultural', 1, true),
                                                                                           ('BUS-0092', 'CN-092-OP', NOW(), '48 asientos, Económico, Aire acondicionado, Ruta Histórica', 2, true),
                                                                                           ('BUS-0093', 'CO-093-PQ', NOW(), '52 asientos, Estándar, Baño, Ruta Arqueológica', 3, false),
                                                                                           ('BUS-0094', 'CP-094-QR', NOW(), '38 asientos, Ejecutivo, Asientos amplios, Ruta Gastronómica', 4, true),
                                                                                           ('BUS-0095', 'CQ-095-RS', NOW(), '42 asientos, Premium, Asientos semi-cama, Ruta Religiosa', 5, true),
                                                                                           ('BUS-0096', 'CR-096-ST', NOW(), '60 asientos, Turístico, Baño, Ruta Ecológica', 6, false),
                                                                                           ('BUS-0097', 'CS-097-TU', NOW(), '40 asientos, Aire acondicionado, WiFi, Ruta Aventura', 7, true),
                                                                                           ('BUS-0098', 'CT-098-UV', NOW(), '50 asientos, Baño, TV, Ruta Deportiva', 8, true),
                                                                                           ('BUS-0099', 'CU-099-VW', NOW(), '30 asientos ejecutivos, Asientos reclinables, Ruta Nocturna', 9, false),
                                                                                           ('BUS-0100', 'CV-100-WX', NOW(), '45 asientos, Aire acondicionado, Baño, Ruta Diurna', 10, true);